[package]
name = "smalda_core"
version = "0.1.0"
edition = "2021"

[dependencies]
regex = "1"
chrono = { version = "0.4", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
strsim = "0.10" # For fuzzy matching
